.gitignore, _pages/jbq/2009/index.md, _pages/jbq/2009/nationals.md, _pages/jbq/2010/index.md, _pages/jbq/2010/nationals.md, _pages/jbq/2011/index.md, _pages/jbq/2011/nationals.md, _pages/jbq/2012/index.md, _pages/jbq/2012/nationals.md, _pages/jbq/2013/index.md, _pages/jbq/2013/nationals.md, _pages/jbq/2014/index.md, _pages/jbq/2014/nationals.md, _pages/jbq/2015/index.md, _pages/jbq/2015/nationals.md, _pages/jbq/2016/index.md, _pages/jbq/2016/nationals.md, _pages/jbq/2017/index.md, _pages/jbq/2017/nationals.md, _pages/jbq/2018/index.md, _pages/jbq/2018/nationals.md, _pages/jbq/2019/index.md, _pages/jbq/2019/nationals.md, _pages/jbq/2020/index.md, _pages/jbq/2021/index.md, _pages/jbq/2021/nationals.md, _pages/jbq/2022/nationals.md, _pages/jbq/index.md
1. Copy the remaining JBQ Nationals from jbq.org/epost to biblequiz.com
2. Add `Gemfile.lock` to `.gitignore`
=> Add remaining JBQ Nationals from ePost

_pages/search.html, search.json
The `/search` page only searches blog posts, rather than the entire site. This change expands the scope of the search.
=> Expand Search to include pages

_pages/apps.md
Windows Store apps are being deprecated in favor of apps in GitHub releases. This change redirects away from the Windows Store in favor of the GitHub release.
=> Use GitHub releases for EZScore and ScoreKeep

_pages/live-events.md, assets/js/live-event-scores.js
* **Moved Source of Live Event Data**
The back-end has been updated to use a different source (scores.biblequiz.com) to allow for better caching and performance. Additional changes are coming related to this.
* **Update TBQ Live Events**
The TBQ Live Events has a link to the 2023 Nationals rather than the menu bar used in JBQ Live Events and the TBQ Current Season. This change fixes the issue.
* **Handle Missing Meets**
If there's a link to an unknown database, it will now get a better error message.
=> Update source of live event scoring data

_pages/contesting-changes.md, _pages/current-season.md, _pages/history/2024/index.md, _pages/history/2024/nationals/index.md, _pages/history/2024/nationals/schedule.md, _pages/history/index.md, _pages/jbq/2024/index.md, _pages/jbq/index.md, index.html
* **Move National Finals**
Migrate the `/national-finals` to `/history/2024/nationals/` to ensure there's a new page for each year.
* **Add 2024 Season to History**
Introduced the 2024 season to the history of both JBQ and TBQ so that the current events are available.
=> Update the current season in BibleQuiz.com

assets/js/live-event-scores.js
A team with index 0 in the `Teams` array is treated as missing entirely when showing the teams dialog.
Explicitly check for `0` for the field to avoid accidentally excluding it.
=> Team with Index 0 is treated as missing

_includes/event-live-scores.html, assets/Test_ScoringReport.json, assets/js/live-event-scores.js
The updated Schedules tab in live scores was designed to display the scores in a mobile friendly way. The old grid system didn't print well and was targeted at the event coordinator. Unfortunately, the existing system forces the user to go to the registration site to look at the database settings.
Introduced a new View button on the page:
This enables several new scenarios:
* **Room View**
Officials often want to see what teams are coming to their room next. The existing view is team-centric, which makes this more difficult. This change introduces a view pivoted by room. Additional improvements in the future may make it easier to determine which room is delaying the match.
* **Grid View**
Displays the old view (currently accessible from the database settings page) to allow event …
=> Add Room and Grid Schedule View to Live Scores

_pages/apps.md
1. Remove the `BETA` tag from the Android EZScore as the app is no longer in beta.
2. Add a link to the full list of releases from GitHub.
=> Update the links on the Apps page

_pages/apps.md
The `All Releases` button on the `/apps` page is currently opening in the same window as the site, losing the user's location. This wasn't an issue with the other buttons as they directly download the installers. This change updates the buttons to open in a new tab.
=> Update Apps page links to open in a new tab

_includes/events-future.html, _pages/upcoming-events/index.md, _pages/upcoming-events/tbq.md, package-lock.json
Once an event stops being "live" (i.e., it's in the past), it's not always obvious for users where the event will appears. This change introduces a button for navigating directly to the season's past events.
**NOTE:** The button will only appear if there is at least one live event.
=> Add a link for the current season's past events

assets/js/live-event-scores.js
If the first meet in the linked list of meets has a larger Meet.Id, that whole meet will be excluded.
=> Fix Room Schedule when Linked Meets are out of order

assets/js/live-event-scores.js
The Schedule Grid doesn't show teams in ranked order, making it more cumbersome to compare between similarly ranked teams. In this change, the teams will be displayed in ranked order if the information is known.
=> Update Schedule Grid to Honor Ranking

_includes/event-live-scores.html, assets/js/live-event-scores.js
If scoring is disabled by the event coordinator, the in-room matches should still be displayed in the live scores. This will be changing in the back-end APIs, but this change is doing the preliminary work.
=> Updating Live Scores to show in-room matches at all times

assets/js/live-event-scores.js
The URLs for scores.biblequiz.com now include a version of the API, which requires updates to the `*.js` scripts.
=> Update the Live Score API URLs

assets/js/live-event-scores.js
The link for in-room scores isn't working for live matches. This change fixes the bug.
=> Allow in-room scoring for live matches

_pages/history/2024/nationals/index.md, assets/js/live-event-scores.js
* Last Modified was showing one month too early as `lastUpdated.getMonth()` returns a base 0 number. This change increments by 1.
* Updated the Nationals page to include a direct link to the scores.
=> Update Nationals and Live Scores

assets/js/live-event-scores.js
A new feature is being added to the registration site to introduce new reports, which require some changes in the live scores as some fields are now null.
=> Add Support for Event Reports in the Live Scores

_includes/event-live-scores.html, assets/js/live-event-scores.js
The new event reports feature on BibleQuiz.com wasn't rendering correctly when there were only teams or only quizzers. This change updates the handling to allow for the teams to be missing.
=> Improve Handling for Event Reports

_includes/hero.html, assets/js/live-event-scores.js
The hero at the top of the page is adding a blank page when printing some of the live event schedules or scores. This change hides the hero when printing which eliminates this issue entirely.
=> Hide the hero when printing live events

_pages/history/2025/scripture-portion.md
The chapter locations mentioned for Festus in the Full Chapter Analysis updates to the portion were incorrect. This corrects the page on biblequiz.com. The newsletter PDFs should also be updated going forward. I see they are PDFs so not sure how those get generated and uploaded to the repo.
=> Update chapter locations for Festus in portion

_includes/event-live-scores.html, assets/js/live-event-scores.js
A new column has been added for quizzers -- `Years Quizzing` -- to be entered by the event coordinator. If this field is present, it needs to be added as a column on the quizzers table.
=> Add Years Quizzing to the Team & Quizzer Stats

_includes/event-live-scores.html, assets/js/live-event-scores.js
When printing single team schedule or scores, the meet name doesn't appear on any other page than the first. This can make it difficult for the coordinator to keep track of the church's division when handing out schedules. This change prefixes the team name with the name of the event in this scenario.
=> Add Prefix for Single Team Schedule or Scores

src/components/auth/AuthButton.tsx
During the sign-up process, the new web site doesn't recognize `/profile/` as the profile page.
=> Fix Profile Recognition

_redirects
Introduce redirects to BibleQuiz.com that will proxy requests to the registration APIs via biblequiz.com. This will avoid CORS triggering when the service is running remotely.
=> Add Redirects

src/content/docs/tbq/Seasons/2026/events.mdx, src/content/docs/tbq/Seasons/2027/events.mdx
The events for the 2026 season were incorrectly left in the 2025 season during the migration to Astro.
1. **Move 2026 Events**
Moved the `events.mdx` from 2025 to 2026, since it includes the 2026 events.
2. **Bring back 2025 events**
Brought back the events from the GitHub history for the 2025 season for historical context.
3. **Add 2027 Placeholder**
Introduced a placeholder for the 2027 season.
=> Move Events to the right location

src/components/scores/EventScoringReportLoader.tsx
The `Stats` tab is being removed when loading a live event due to incorrect indexing.
=> Fix issue where Stats tab is removed
